extensions:
  bearertokenauth:
    token: "${env:COLLECTOR_TOKEN}"

receivers:
  otlp:
    protocols:
      # grpc:
      #   endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: bearertokenauth

processors:
  batch:
    timeout: 60s
    send_batch_size: 2048

exporters:
  otlphttp/victoriametrics:
    endpoint: "http://victoriametrics:8428/opentelemetry"
    tls:
      insecure: true

  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  debug:
    verbosity: basic
  
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

service:
  extensions: [bearertokenauth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victoriametrics, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, debug]