receivers:
  otlp:
    protocols:
      # grpc:
      #   endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  file:
    path: /var/lib/otelcol/telemetry.json
    flush_interval: 60s
    rotation:
      max_megabytes: 100
      max_days: 7
      # max_backups: 5
      localtime: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
    metrics:
      receivers: [otlp]
      exporters: [file]
    logs:
      receivers: [otlp]
      exporters: [file]
